
namespace Business.Configurations;

//Entire class generated by ChatGPT 4o. The code limits the  times I need to state the path and file name for saving and loading the file holding the contacts.

public class FileServiceConfig
{
    public string DirectoryPath { get; set; } = "C:\\Projects\\ContactList\\MainApp\\bin\\Debug\\net8.0\\Data";
    public string FileName { get; set; } = "contactList.json";
}

